### ISSUE TITLE
How to configure the provider during cluster creation?

### ISSUE THREAD

**Issue by encron** [kubernetes-sigs/aws-encryption-provider#18]
**What would you like to be added**:

Currently the README only describes how to add the encryption provider to a running cluster by first deploying the provider and then changing the api-server flags. I was wondering how/if it is supposed to be deployed when starting a new cluster, so already starting the `apiserver` with the encryption enabled. 

For example, I am using kubeadm to provision my cluster and would add these lines to the config file:

```
  extraArgs:
    cloud-provider: aws
    encryption-provider-config: /etc/kubernetes/encryption-config.yml
  extraVolumes:
  - name: "encryption-config"
    hostPath: " /etc/kubernetes/encryption-config.yml"
    mountPath: "/etc/kubernetes/encryption-config.yml"
    readOnly: true
    pathType: File
```

This will start the apiserver with the encryption-config mount and the `--encryption-provider-config` flag and after the `apiserver` is live, I would deploy the encryption-provider.  

Is this possible or should the provider always be deployed first? From what I understand, the unix socket will need to be there before the `apiserver` can start with the `--encryption-provider-config` flag which means it won't be possible.  

**Why is this needed**:

It's not clear on how to configure the encryption-provider on a fresh cluster or if it's even possible.
