### ISSUE TITLE
unknown shorthand flag: 'k' in -key=<role_arn> error

### ISSUE THREAD

**Issue by cparadal** [kubernetes-sigs/aws-encryption-provider#66]
**What happened**:
I am unable to get the AWS Encryption Provider static pods to start. They seem to fail with the below error.

```
unknown shorthand flag: 'k' in -key=<role_arn>
Usage of /aws-encryption-provider:
      --burst-limit int                     number of tokens that can be consumed in a single call
      --debug                               Print debug level logs
      --encryption-context stringToString   AWS KMS Encryption Context (e.g. 'a=b,c=d') (default [])
      --health-port string                  healthcheck port (default ":8080")
      --healthz-path string                 healthcheck path (default "/healthz")
      --key string                          AWS KMS Key
      --kms-endpoint string                 use this KMS endpoint instead of the one generated by AWS sdk
      --listen string                       GRPC listen address (default "/var/run/kmsplugin/socket.sock")
      --qps-limit int                       number of requests per second to allow for KMS API calls (0 to not rate limit)
      --region string                       AWS Region (default "us-east-1")
unknown shorthand flag: 'k' in -key=<role_arn>
```

**What you expected to happen**:
That the Encryption Provider pod starts successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Build the AWS Encryption Provider image from the latest Dockerfile provided and try to deploy it as a static pod on Kubernetes, using the below pod spec.

```
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-encryption-provider
  namespace: kube-system
spec:
  containers:
  - image: <aws_encryption_provider_image> 
    name: aws-encryption-provider
    command:
    - /aws-encryption-provider
    - -key=<role_arn>
    - -region=eu-west-1
    - -listen=/var/run/kmsplugin/socket.sock
    - -health-port=:8083
    ports:
    - containerPort: 8083
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8083
    volumeMounts:
    - mountPath: /var/run/kmsplugin
      name: var-run-kmsplugin
  hostNetwork: true
  volumes:
  - name: var-run-kmsplugin
    hostPath:
      path: /var/run/kmsplugin
      type: DirectoryOrCreate
```

**Anything else we need to know?**:

**Environment**:
Kubernetes (built with kubeadm).

- Kubernetes version (use `kubectl version`):
v1.15.11

- Encryption provider plugin version:
Latest available on Github

- Cloud provider configuration:

- OS (e.g: `cat /etc/os-release`):
18.04.3 LTS (Bionic Beaver)

- Kernel (e.g. `uname -a`):
 4.15.0-1057-aws

- Install tools:
Kubeadm

- Others:
